import './globals.css'
import Link from 'next/link'
import NavBar from './nav-bar'  // custom componest used as <Comp_Name />

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />  
        <div>{children}</div>
      </body>
    </html>
  )
}
