import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav style={{ padding : "10px 0 10px 0"}}>
          <Link href="/" style={{ padding : "0 5px 0 0"}}>
            Home
          </Link>
          <Link href="/posts" style={{ padding : "0 5px 0 0"}}>
            Posts
          </Link>
          <Link href="/users" style={{ padding : "0 5px 0 0"}}>
            Users
          </Link>
        </nav>

        {children} 
      </body>
    </html>
  )
}
